### ISSUE TITLE
titel change

### ISSUE THREAD

**Issue by IvoBrandjes** [GIDSOpenStandaarden/GIDS-SNS-RI-Portal-Java#1]
@rolandgroen @RemyHeadease,  Remy has described this repository in the category SNS/ Community for our [Signpost](https://github.com/GIDSOpenStandaarden/Signpost). If that is the case, than the titel should be more in line of: "OpenSNS-Community-RIPortal-Java". See our [template](https://github.com/GIDSOpenStandaarden/GIDSOpenStandaarden-Templates) Agree?

Before we can add this repository to the Signpost, we need to have a description of the repositorie in the readme file. In stead of a description in the Signpost. The Signpost is to help people to find the correct repository in context to other categories en repositories, not to give complete descriptions. Agree?

I presume that repository: https://github.com/GIDSOpenStandaarden/GIDS-SNS-Solid-Client-Java has a close connection to this repository. And that what I said above also applies here? The titel should be more in line of: "OpenSNS-Community-SolidClient-Java"?

Please advise/ decide on the correct category, the correct titels and add the descriptions tot the readme files in the repositories. Let me know the outcome in basecamp and I wil edit the Signpost.  

Description Remy gave: 

GIDS-SNS-RI-Portal-Java - Reference implementation of a portal to: 
- List e-health tasks and use HTI to anonymously launch these tasks.
- Connect to a Solid POD
- Give read / write access to Solid POD

**Comment by RemyHeadease** [comment]
Hi @IvoBrandjes ,

Regarding the naming convention:
- It depends how you look at the repo's, both could be seen as OpenSNS as GIDS. They have been developed within the OpenSNS setting, but now, as we move forward and get in contact with other initiatives they are being seen as shared functions:
  - The reference portal can be used in any context: Clientportal / Neighborhood platform. 
  - Solid can be used within any context: Healthcare, social life (public and private), banking etc etc..

In my opinion it's stronger to see them as shared functions, that is if we have the same opinion on what a shared function is. 
Do you want to have a call on this, before me changing it?

**Comment by IvoBrandjes** [comment]
@RemyHeadease clear, we made a choice to stick to OpenSNS for now, like HTI we move forward with these repositories if SNS-community is succeeded, relation to SNS is important to complete the story. Explain/ discuss details with you in call/Basecamp, so we can decide how to change the titel and information in the repositories and how we will change the github Signpost for now. This issue is closed.
